name: Follow latest

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *

jobs:
  follow:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x
      - name: Install
        run: npm ci
      - name: Make dataset
        run: scripts/follow.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
